[package]
name = "cargo-flaky"
version = "0.1.0"
authors = ["marin postma <postma.marin@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
once_cell = "1.7.2"
regex = "1.5.4"
structopt = "0.3.21"
subprocess = "0.2.7"
